@httpServer = http://localhost:3000
@httpsServer = https://localhost:3001

### Start a http Server
GET {{httpServer}}/myapp/?search=test HTTP/1.1
Content-Type: application/json

### Start a https Server
GET {{httpsServer}}/myapp/?search=test HTTP/1.1
Content-Type: application/json

### Parse payload
POST {{httpServer}}/myapp/?search=test HTTP/1.1
Content-Type: application/json

{
  "name": "jane"
}

### Route requests http
POST {{httpServer}}/sample HTTP/1.1
Content-Type: application/json

{
  "name": "jane"
}

### Route requests https
POST {{httpsServer}}/sample HTTP/1.1
Content-Type: application/json

{
  "name": "jane"
}

### Route requests
POST {{httpServer}}/notfound HTTP/1.1
Content-Type: application/json

{
  "name": "jane"
}

### http Service 1
GET {{httpServer}}/ping HTTP/1.1
Content-Type: application/json

### https Service 1
GET {{httpsServer}}/ping HTTP/1.1
Content-Type: application/json